#!/usr/bin/env node
'use strict';
const {projectFileName} = require('./services/constants');
const {
  getCurrentDay,
  createDay,
  downloadInput,
} = require('./services/advent-of-code-utils');
const {scriptName} = require('yargs');

const positionalArgs = {
  day: {
    type: 'number',
    default: getCurrentDay(),
    describe: 'The number of the day to create',
  },
};

scriptName(projectFileName)
  .usage('$0 <cmd> [args]')
  .command('create [day]', 'Creates a new day for advent of code', yargs => {
    yargs.positional('day', positionalArgs.day);
  }, async ({day}) => {
    await createDay(day);
  })
  .command('download [day]', 'Downloads the input for the day', yargs => {
    yargs.positional('day', positionalArgs.day);
  }, async ({day}) => {
    await downloadInput(day);
  })
  .fail((msg, err, yargs) => {
    console.log(msg, typeof err);
  })
  .version(false)
  .help()
  .argv;
